version: "3"
services:
  hub:
    image: selenium/hub:3.141.59
    ports:
      - 4444:4444
  chrome:
    image: selenium/node-chrome-debug:3.141.59
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
    ports:
      - 5900:5900
  firefox:
    image: selenium/node-firefox-debug:3.141.59
    shm_size: '512m'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
    ports:
      - 5901:5900
  OnlineReporting-chrome:
    image: 10.0.3.5:5000/sdt/pega-automated-tests 
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=pegaTestCases
    volumes:
      - ./test-results/registration-result:/usr/share/police-automation/Reports
  OnlineReporting-firefox:
    image: 10.0.3.5:5000/sdt/pega-automated-tests 
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - MODULE=pegaTestCases
    volumes:
      - ./test-results/registration-result:/usr/share/police-automation/Reports
